## **Домашнее задание 1**

*   Номер задачи - заголовок 2
*   Номер подзадачи - заголовок 3
*   Предоставленные наборы данных оформляйте, как код

`Code`

## **Домашнее задание 2**
На складе лежат разные фрукты в разном количестве. Нужно написать функцию, которая на вход принимает любое количество названий фруктов и их количество, а возвращает общее количество фруктов на складе.

In [11]:
def fruit_count(**kwargs):
    {print(f"Количество {name} - {values}")
     for name, values in kwargs.items()}
    return print(f'Всего: {sum(kwargs.values())}')
fruit_count (pear = 10, apple = 18, grape = 15, kiwi = 25)

Количество pear - 10
Количество apple - 18
Количество grape - 15
Количество kiwi - 25
Всего: 68

## **Домашнее задание 3**
Дан список с затратами на рекламу. Но в данных есть ошибки, некоторые затраты имеют отрицательную величину. Удалите такие значения из списка и посчитайте суммарные затраты.

`[100, 125, -90, 345, 655, -1, 0, 200]`

Используйте *list comprehensions*.

In [4]:
costs = [100, 125, -90, 345, 655, -1, 0, 200]
correct_costs = [a for a in costs if a > 0]
print(correct_costs)

[100, 125, 345, 655, 200]

In [5]:
print(sum(correct_costs))

1425

## **Домашнее задание 4**
Даны два списка.
Дата покупки 
`['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']`

Суммы покупок по датам 
`[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]`

### **4.1 Найдите, какая выручка у компании в ноябре**

Используйте *list comprehensions*.

In [7]:
date_purchase = ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']
sum_purchase = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

print(sum([m for d, m in zip(date_purchase, sum_purchase) if d[5:7] == "11"]))

25098

### **4.2 Найдите выручку компании в зависимости от месяца** 
Для этого напишите функцию, которая на вход принимает список с датами и список с выручкой, а на выходе словарь, где ключи - это месяцы, а значения - это выручка. 
Используйте аннотирование типов.

In [8]:
date_purchase = ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']
sum_purchase = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

def sum_in_month(date: list, sum: list) -> dict:
    res = {}
    for d, m in zip(date, sum):
        if d[5:7] in res.keys():
            res[d[5:7]] = res[d[5:7]] + m
        else:
            res[d[5:7]] = m
    return res
 
print(sum_in_month(date_purchase, sum_purchase))

{'09': 25647, '12': 45452, '10': 28645, '11': 25098}